// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using picpay_desafio.Infra;

#nullable disable

namespace picpay_desafio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220091147_rename_userType_to_user_type")]
    partial class rename_userType_to_user_type
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("picpay_desafio.Models.CarteiraEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount_account")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("document")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_type");

                    b.HasKey("id");

                    b.HasIndex("document", "email")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("picpay_desafio.Models.TransferenciaEntity", b =>
                {
                    b.Property<Guid>("transaction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("receiver_id")
                        .HasColumnType("int");

                    b.Property<int>("sender_id")
                        .HasColumnType("int");

                    b.HasKey("transaction_id");

                    b.HasIndex("receiver_id");

                    b.HasIndex("sender_id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("picpay_desafio.Models.TransferenciaEntity", b =>
                {
                    b.HasOne("picpay_desafio.Models.CarteiraEntity", "receiver")
                        .WithMany()
                        .HasForeignKey("receiver_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Receiver");

                    b.HasOne("picpay_desafio.Models.CarteiraEntity", "sender")
                        .WithMany()
                        .HasForeignKey("sender_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Sender");

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });
#pragma warning restore 612, 618
        }
    }
}
